<form action="index.php" method="post">
    
    <fieldset>
        <label>Prénom</label>
        <input type="text" name="firstName"/>
    </fieldset>
    <fieldset>
        <label>Nom</label>
        <input type="text" name="lastName"/>
    </fieldset>
    <fieldset>
        <label>Email</label>
        <input type="email" name="email"/>
    </fieldset>
    <fieldset>
        <label>Mot de passe</label>
        <input type="password" name="password"/>
    </fieldset>
    <fieldset>
        <label>Confirmez votre mot de passe</label>
        <input type="password" name="confirmPassword"/>
    </fieldset>
    <input type="hidden" name="formName"/>
    <input type="submit" value="S'enregistrer"/>
    

</form>